[package]
name        = "Flix wrappers over Charset and Locale from the JDK using new the Adaptor code."
description = "Flix Charset and Locale wrappers"
version     = "0.2.0"
flix        = "0.45.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


